name: GitHub Actions

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Setup
      run: ci/gh-actions/setup.sh
    - name: Configure
      run: ci/gh-actions/run.sh configure
    - name: Build
      run: ci/gh-actions/run.sh build
    - name: Test
      run: ci/gh-actions/run.sh test
    - name: Install
      run: ci/gh-actions/run.sh install

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Setup
      run: ci/gh-actions/setup.sh
    - name: Configure
      run: ci/gh-actions/run.sh configure
    - name: Build
      run: ci/gh-actions/run.sh build
    - name: Test
      run: ci/gh-actions/run.sh test
    - name: Install
      run: ci/gh-actions/run.sh install
